const error = new Error();

throw 'error';
~~~~~~~~~~~~~~ [failure]

throw error;
~~~~~~~~~~~~ [failure]

throw new Error();
~~~~~~~~~~~~~~~~~~ [failure]

[failure]: Unexpected throw, throwing exceptions is not functional.
