const error = new Error();

function foo(): Promise<number> {
    if (Math.random() > 0.5) {
        return Promise.reject(new Error("bar"))
               ~~~~~~~~~~~~~~ [failure]
    }
    return Promise.resolve(10)
}

function bar(): Promise<number | Error> {
    if (Math.random() > 0.5) {
        return Promise.resolve(new Error("foo"))
    }
    return Promise.resolve(10)
}

[failure]: Unexpected reject, return an error instead.
